Support image source
Projektanker/Icons.Avalonia pull request #96
Opened 2023-12-02 15:52 UTC by OmidID

The `IconImageSource` allow developers to use it as `IImage` in the code or xaml file.
Example: 
```xml
<Image>
	<Image.Source>
		<i:IconImageSource Value="fa-solid fa-address-card" Brush="Black"></i:IconImageSource>
	</Image.Source>
</Image>
```

```csharp
myImage.Source = new IconImageSource { Value = "fa-solid fa-address-card", Brush = Brushes.Black };
```

2023-12-05 15:11 UTC, SebastianRumohr requested changes
Thank you very much for your pull request to fix the issue mentioned in #15.
Unfortunatly, your solution would reintroduce a bug that was fixed with [version 8.0.0](https://github.com/Projektanker/Icons.Avalonia/releases/tag/v8.0.0)
> Do not stretch icon paths to full size. Otherwise icons like [circle-medium](https://pictogrammers.com/library/mdi/icon/circle-medium/) won't be rendered as expected. ([8182200](https://github.com/Projektanker/Icons.Avalonia/commit/81822006afcee08301e93b9464d9055b9ce72f28))

I don't know how to support this with a geometry drawing right now. 

One other thing: In my opinion you should create a new `DrawingImage` each time a property changes. Otherwise changes in `Value` would not be rendered.
See [old Icon.xaml](https://github.com/Projektanker/Icons.Avalonia/blob/c99f654b0c88658aeb7437e3acb93330cceda23b/src/Projektanker.Icons.Avalonia/Icon.axaml.cs#L54) and an old issue #7.
Or did you test it's dynamic behavior?

Thank's again for your pull request. Im looking forward to your updates.

2023-12-06 14:33 UTC, SebastianRumohr approved these changes
@OmidID you got me thinking. I really like the idea of having an `IconImage` implementing the `IImage` interface.
I will use your code as a starting point to refactor the way the icons are rendered. After that you can use the `<i:Icon>` as a complete icon or just the `<i:IconImage>` inside an image or wherever an `IImage` is required.

2023-12-06 14:33 UTC, merged

2023-12-06 17:26 UTC, SebastianRumohr commented
You are right. The `DrawingImage` is a pretty basic component.
Maybe you could use `object` or `AvaloniaObject` instead of `IImage` for the `Icon` property in your `SideMenuItem` class. The [Avalonia.Controls.MenuItem](https://reference.avaloniaui.net/api/Avalonia.Controls/MenuItem/84F8427F) uses `object` and uses an `ObjectPresenter` to render the icon in the [Avalonia.Themes.Fluent/Controls/MenuItem.xaml](https://github.com/AvaloniaUI/Avalonia/blob/8a4c89fe8aec969068467ba29f089f6559f16105/src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml#L91C50-L91C50).

2023-12-06 18:41 UTC, OmidID commented
Yes. I think for that. But the Shell used in some real productions. and I don't want to have break changes for small thing now.
Maybe later I going to support both or maybe complex side menu item. 
But I wanted to show the example of it.